# Generated by Django 3.0.3 on 2020-02-24 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200224_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='power',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
