# Generated by Django 3.0.3 on 2020-02-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_hero_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='power',
        ),
    ]
